name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-worm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-vcpkg
      - run: cargo fmt --all -- --check
      - run: cargo vcpkg --verbose build
      - run: cargo clippy --all-targets --all-features
      - run: cargo build --example worm --release
      - run: copy target/release/examples/worm.exe worm.exe
      - uses: actions/upload-artifact@v4
        with:
          name: worm
          path: |
            assets/
            worm.exe
          if-no-files-found: error
          overwrite: true
          retention-days: 90
#
